# Generated by Django 3.0.6 on 2020-07-03 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CommodityApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='commodities',
            old_name='user_id',
            new_name='username_id',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='user_id',
            new_name='username_id',
        ),
        migrations.RenameField(
            model_name='farmer',
            old_name='user_id',
            new_name='username_id',
        ),
        migrations.RenameField(
            model_name='manufacturer',
            old_name='user_id',
            new_name='username_id',
        ),
        migrations.RenameField(
            model_name='requirement',
            old_name='user_id',
            new_name='username_id',
        ),
        migrations.RemoveField(
            model_name='usertype',
            name='user_id',
        ),
        migrations.AddField(
            model_name='usertype',
            name='username',
            field=models.CharField(default=' ', max_length=100),
            preserve_default=False,
        ),
    ]
