# Generated by Django 3.0.6 on 2020-07-03 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CommodityApp', '0002_auto_20200703_1203'),
    ]

    operations = [
        migrations.AddField(
            model_name='commodities',
            name='description',
            field=models.CharField(default=' ', max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='commodities',
            name='rating',
            field=models.FloatField(default=0.0),
        ),
    ]
