# Generated by Django 3.0.3 on 2020-07-03 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CommodityApp', '0003_auto_20200703_1321'),
    ]

    operations = [
        migrations.AddField(
            model_name='commodities',
            name='breed',
            field=models.CharField(default=' ', max_length=200),
        ),
    ]
