# Generated by Django 3.0.6 on 2020-07-03 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CommodityApp', '0005_auto_20200703_1411'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='priceperunit',
            new_name='amount',
        ),
        migrations.AddField(
            model_name='commodities',
            name='type',
            field=models.CharField(choices=[('FRUIT', 'Fruit'), ('VEGIES', 'VEGETABLES'), ('PULSES', 'Pulses'), ('CEREAL', 'Cereal'), ('OTHERS', 'OTHERS')], default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='price',
            field=models.FloatField(default=0.0),
        ),
    ]
