# Generated by Django 3.0.6 on 2020-07-03 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CommodityApp', '0006_auto_20200703_1643'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commodities',
            name='type',
            field=models.CharField(choices=[('FRUIT', 'Fruit'), ('VEGIES', 'Vegetables'), ('PULSES', 'Pulses'), ('CEREAL', 'Cereal'), ('OTHERS', 'Others')], max_length=100),
        ),
    ]
