# Generated by Django 3.0.6 on 2020-07-03 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CommodityApp', '0007_auto_20200703_1645'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='ordercode',
            field=models.CharField(default='', max_length=100),
        ),
    ]
