# Generated by Django 3.0.6 on 2020-07-03 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CommodityApp', '0008_order_ordercode'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='comcode',
            field=models.CharField(default='', max_length=100),
        ),
    ]
