# Generated by Django 3.0.6 on 2020-07-03 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CommodityApp', '0009_order_comcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='bill',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='order',
            name='breed',
            field=models.CharField(default=' ', max_length=200),
        ),
        migrations.AddField(
            model_name='order',
            name='name',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='tax',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='order',
            name='total',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='order',
            name='type',
            field=models.CharField(choices=[('FRUIT', 'Fruit'), ('VEGIES', 'Vegetables'), ('PULSES', 'Pulses'), ('CEREAL', 'Cereal'), ('OTHERS', 'Others')], default='', max_length=100),
            preserve_default=False,
        ),
    ]
