# Generated by Django 3.0.6 on 2020-07-03 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CommodityApp', '0010_auto_20200703_2054'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=200)),
                ('comcode', models.CharField(max_length=100)),
                ('breed', models.CharField(default=' ', max_length=200)),
                ('weight', models.FloatField()),
            ],
        ),
    ]
