# Generated by Django 3.0.6 on 2020-07-03 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CommodityApp', '0011_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='type',
            field=models.CharField(choices=[('FRUIT', 'Fruit'), ('VEGIES', 'Vegetables'), ('PULSES', 'Pulses'), ('CEREAL', 'Cereal'), ('OTHERS', 'Others')], default='', max_length=100),
            preserve_default=False,
        ),
    ]
