# Generated by Django 3.0.6 on 2020-07-04 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CommodityApp', '0012_cart_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='perishable',
            field=models.BooleanField(default=False),
        ),
    ]
