# Generated by Django 3.0.6 on 2020-07-04 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CommodityApp', '0015_distance'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='deliveryprice',
            field=models.FloatField(default=0.0),
        ),
    ]
