# Generated by Django 3.0.6 on 2020-07-04 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CommodityApp', '0016_order_deliveryprice'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='couriername',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='order',
            name='deliveryboy',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='order',
            name='truckname',
            field=models.CharField(default='', max_length=100),
        ),
    ]
