# Generated by Django 3.0.6 on 2020-07-04 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CommodityApp', '0017_auto_20200704_1638'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='expecteddate',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='order',
            name='orderstatus',
            field=models.CharField(choices=[('Yet to be shipped', 'Yet to be shipped'), ('Shipped', 'Shipped'), ('Delivered', 'Delivered')], default='', max_length=20),
        ),
    ]
