# Generated by Django 3.0.6 on 2020-07-04 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CommodityApp', '0018_auto_20200704_1648'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='orderstatus',
            field=models.CharField(choices=[('Yet to be shipped', 'Yet to be shipped'), ('On the way', 'On the way'), ('Shipped', 'Shipped'), ('Delivered', 'Delivered')], default='', max_length=20),
        ),
    ]
