# Generated by Django 3.0.6 on 2020-07-04 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CommodityApp', '0019_auto_20200704_1906'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ratings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comcode', models.CharField(max_length=100)),
                ('rating', models.FloatField()),
                ('desc', models.CharField(max_length=100)),
            ],
        ),
    ]
