# Generated by Django 3.0.6 on 2020-07-04 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DeliverySystem', '0003_auto_20200704_1511'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryboy',
            name='orders',
            field=models.IntegerField(default=0),
        ),
    ]
