# Generated by Django 3.0.6 on 2020-07-04 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DeliverySystem', '0005_courierorder_deliveryorder_truckorder'),
    ]

    operations = [
        migrations.AddField(
            model_name='courierorder',
            name='status',
            field=models.CharField(choices=[('PENDING', 'PENDING'), ('DELIVERED', 'DELIVERED')], default='', max_length=10),
            preserve_default=False,
        ),
    ]
