# Generated by Django 3.0.6 on 2020-07-04 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DeliverySystem', '0008_deliveryorder_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='truckorder',
            name='status',
            field=models.CharField(choices=[('PENDING', 'PENDING'), ('DELIVERED', 'DELIVERED')], default='PENDING', max_length=10),
        ),
    ]
